package com.revplay.musicplatform.download.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.download.entity.SongDownload;
import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS song_downloads",
        "CREATE TABLE song_downloads (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT NOT NULL, " +
                "song_id BIGINT NOT NULL, " +
                "downloaded_at TIMESTAMP NOT NULL, " +
                "CONSTRAINT uk_song_download_user_song UNIQUE (user_id, song_id))"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Tag("integration")
class SongDownloadRepositoryTest {

    private static final Long USER_ID = 15L;
    private static final Long SONG_ID = 25L;
    private static final Long OTHER_USER_ID = 16L;

    private final SongDownloadRepository songDownloadRepository;

    @Autowired
    SongDownloadRepositoryTest(SongDownloadRepository songDownloadRepository) {
        this.songDownloadRepository = songDownloadRepository;
    }

    @Test
    @DisplayName("existsByUserIdAndSongId returns true for saved download")
    void existsByUserIdAndSongIdReturnsTrue() {
        SongDownload songDownload = new SongDownload();
        songDownload.setUserId(USER_ID);
        songDownload.setSongId(SONG_ID);
        songDownload.setDownloadedAt(LocalDateTime.now());
        songDownloadRepository.save(songDownload);

        boolean exists = songDownloadRepository.existsByUserIdAndSongId(USER_ID, SONG_ID);

        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("existsByUserIdAndSongId returns false for non matching user")
    void existsByUserIdAndSongIdReturnsFalseForDifferentUser() {
        SongDownload songDownload = new SongDownload();
        songDownload.setUserId(USER_ID);
        songDownload.setSongId(SONG_ID);
        songDownload.setDownloadedAt(LocalDateTime.now());
        songDownloadRepository.save(songDownload);

        boolean exists = songDownloadRepository.existsByUserIdAndSongId(OTHER_USER_ID, SONG_ID);

        assertThat(exists).isFalse();
    }
}
