package com.revplay.musicplatform.playlist.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.playlist.entity.Playlist;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
})
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Tag("integration")
class PlaylistRepositoryTest {

    private final PlaylistRepository playlistRepository;

    @Autowired
    PlaylistRepositoryTest(PlaylistRepository playlistRepository) {
        this.playlistRepository = playlistRepository;
    }

    @Test
    @DisplayName("findAccessiblePlaylists returns public and own private playlists")
    @Sql(statements = {
            "DROP TABLE IF EXISTS playlists",
            "CREATE TABLE playlists (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_id BIGINT NOT NULL, " +
                    "name VARCHAR(100) NOT NULL, " +
                    "description VARCHAR(500), " +
                    "is_public BOOLEAN NOT NULL, " +
                    "is_active BOOLEAN NOT NULL, " +
                    "created_at TIMESTAMP, " +
                    "updated_at TIMESTAMP, " +
                    "version BIGINT)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(1, 10, 'Public A', 'desc', TRUE, TRUE, TIMESTAMP '2025-01-01 10:00:00', TIMESTAMP '2025-01-01 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(2, 10, 'Private A', 'desc', FALSE, TRUE, TIMESTAMP '2025-01-02 10:00:00', TIMESTAMP '2025-01-02 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(3, 11, 'Public B', 'desc', TRUE, TRUE, TIMESTAMP '2025-01-03 10:00:00', TIMESTAMP '2025-01-03 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(4, 11, 'Inactive', 'desc', TRUE, FALSE, TIMESTAMP '2025-01-04 10:00:00', TIMESTAMP '2025-01-04 10:00:00', 0)"
    }, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
    void findAccessiblePlaylistsReturnsPublicAndOwnPrivate() {
        Page<Playlist> page = playlistRepository.findAccessiblePlaylists(10L, PageRequest.of(0, 10));
        List<Playlist> results = page.getContent();

        assertThat(results)
                .extracting(Playlist::getId)
                .containsExactly(3L, 2L, 1L);
    }

    @Test
    @DisplayName("searchPublicPlaylistsByKeyword matches name or description")
    @Sql(statements = {
            "DROP TABLE IF EXISTS playlists",
            "CREATE TABLE playlists (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_id BIGINT NOT NULL, " +
                    "name VARCHAR(100) NOT NULL, " +
                    "description VARCHAR(500), " +
                    "is_public BOOLEAN NOT NULL, " +
                    "is_active BOOLEAN NOT NULL, " +
                    "created_at TIMESTAMP, " +
                    "updated_at TIMESTAMP, " +
                    "version BIGINT)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(1, 10, 'Morning Mix', 'desc', TRUE, TRUE, TIMESTAMP '2025-01-01 10:00:00', TIMESTAMP '2025-01-01 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(2, 10, 'Focus', 'Best mix for work', TRUE, TRUE, TIMESTAMP '2025-01-02 10:00:00', TIMESTAMP '2025-01-02 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(3, 10, 'Hidden', 'secret', FALSE, TRUE, TIMESTAMP '2025-01-03 10:00:00', TIMESTAMP '2025-01-03 10:00:00', 0)",
            "INSERT INTO playlists (id, user_id, name, description, is_public, is_active, created_at, updated_at, version) VALUES " +
                    "(4, 10, 'Old Mix', 'desc', TRUE, FALSE, TIMESTAMP '2025-01-04 10:00:00', TIMESTAMP '2025-01-04 10:00:00', 0)"
    }, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
    void searchPublicPlaylistsByKeywordMatchesNameOrDescription() {
        Page<Playlist> page = playlistRepository.searchPublicPlaylistsByKeyword("mix", PageRequest.of(0, 10));

        assertThat(page.getContent())
                .extracting(Playlist::getId)
                .containsExactly(2L, 1L);
    }
}
