package com.revplay.musicplatform.playlist.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.playlist.entity.PlaylistSong;
import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS playlist_songs",
        "CREATE TABLE playlist_songs (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "playlist_id BIGINT NOT NULL, " +
                "song_id BIGINT NOT NULL, " +
                "position INT NOT NULL, " +
                "added_at TIMESTAMP, " +
                "version BIGINT, " +
                "CONSTRAINT uk_playlist_song UNIQUE (playlist_id, song_id))"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Tag("integration")
class PlaylistSongRepositoryTest {

    private final PlaylistSongRepository playlistSongRepository;

    @Autowired
    PlaylistSongRepositoryTest(PlaylistSongRepository playlistSongRepository) {
        this.playlistSongRepository = playlistSongRepository;
    }

    @Test
    @DisplayName("deleteByPlaylistIdAndSongId removes only matching row")
    void deleteByPlaylistIdAndSongIdRemovesOnlyMatchingRow() {
        PlaylistSong song1 = new PlaylistSong();
        song1.setPlaylistId(1L);
        song1.setSongId(11L);
        song1.setPosition(1);
        song1.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song1);

        PlaylistSong song2 = new PlaylistSong();
        song2.setPlaylistId(1L);
        song2.setSongId(12L);
        song2.setPosition(2);
        song2.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song2);

        PlaylistSong song3 = new PlaylistSong();
        song3.setPlaylistId(2L);
        song3.setSongId(13L);
        song3.setPosition(1);
        song3.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song3);

        playlistSongRepository.deleteByPlaylistIdAndSongId(1L, 11L);

        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(1L, 11L)).isFalse();
        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(1L, 12L)).isTrue();
        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(2L, 13L)).isTrue();
    }

    @Test
    @DisplayName("deleteAllByPlaylistId removes all songs for playlist")
    void deleteAllByPlaylistIdRemovesAllSongsForPlaylist() {
        PlaylistSong song1 = new PlaylistSong();
        song1.setPlaylistId(3L);
        song1.setSongId(21L);
        song1.setPosition(1);
        song1.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song1);

        PlaylistSong song2 = new PlaylistSong();
        song2.setPlaylistId(3L);
        song2.setSongId(22L);
        song2.setPosition(2);
        song2.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song2);

        PlaylistSong song3 = new PlaylistSong();
        song3.setPlaylistId(4L);
        song3.setSongId(23L);
        song3.setPosition(1);
        song3.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song3);

        playlistSongRepository.deleteAllByPlaylistId(3L);

        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(3L, 21L)).isFalse();
        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(3L, 22L)).isFalse();
        assertThat(playlistSongRepository.existsByPlaylistIdAndSongId(4L, 23L)).isTrue();
    }

    @Test
    @DisplayName("findMaxPositionByPlaylistId returns max position or zero")
    void findMaxPositionByPlaylistIdReturnsMaxOrZero() {
        Integer emptyMax = playlistSongRepository.findMaxPositionByPlaylistId(5L);
        assertThat(emptyMax).isZero();

        PlaylistSong song1 = new PlaylistSong();
        song1.setPlaylistId(5L);
        song1.setSongId(31L);
        song1.setPosition(4);
        song1.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song1);

        PlaylistSong song2 = new PlaylistSong();
        song2.setPlaylistId(5L);
        song2.setSongId(32L);
        song2.setPosition(7);
        song2.setAddedAt(LocalDateTime.now());
        playlistSongRepository.save(song2);

        Integer maxPosition = playlistSongRepository.findMaxPositionByPlaylistId(5L);
        assertThat(maxPosition).isEqualTo(7);
    }
}
