package com.revplay.musicplatform.catalog.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.catalog.entity.Podcast;
import com.revplay.musicplatform.catalog.enums.ContentVisibility;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.datasource.url=jdbc:h2:mem:podcastrepo;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
})
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS podcast_episodes",
        "DROP TABLE IF EXISTS podcasts",
        "CREATE TABLE podcasts (" +
                "podcast_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "artist_id BIGINT NOT NULL, " +
                "category_id BIGINT NOT NULL, " +
                "title VARCHAR(255) NOT NULL, " +
                "description VARCHAR(1000), " +
                "cover_art_url VARCHAR(1000), " +
                "visibility VARCHAR(50), " +
                "created_at TIMESTAMP, " +
                "is_active BOOLEAN, " +
                "version BIGINT)",
        "CREATE TABLE podcast_episodes (" +
                "episode_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "podcast_id BIGINT NOT NULL, " +
                "title VARCHAR(255) NOT NULL, " +
                "audio_url VARCHAR(1000) NOT NULL, " +
                "duration_seconds INT NOT NULL, " +
                "release_date DATE, " +
                "version BIGINT)"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Tag("integration")
class PodcastRepositoryTest {

    private final PodcastRepository podcastRepository;
    private final JdbcTemplate jdbcTemplate;

    @Autowired
    PodcastRepositoryTest(PodcastRepository podcastRepository, JdbcTemplate jdbcTemplate) {
        this.podcastRepository = podcastRepository;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Test
    @DisplayName("findByArtistIdAndIsActiveTrue returns only active podcasts for artist")
    void findByArtistIdAndIsActiveTrueReturnsOnlyActive() {
        Podcast active = new Podcast();
        active.setArtistId(10L);
        active.setCategoryId(1L);
        active.setTitle("Active Podcast");
        active.setDescription("desc");
        active.setVisibility(ContentVisibility.PUBLIC);
        active.setIsActive(true);
        podcastRepository.save(active);

        Podcast inactive = new Podcast();
        inactive.setArtistId(10L);
        inactive.setCategoryId(1L);
        inactive.setTitle("Inactive Podcast");
        inactive.setVisibility(ContentVisibility.PUBLIC);
        inactive.setIsActive(false);
        podcastRepository.save(inactive);

        Podcast otherArtist = new Podcast();
        otherArtist.setArtistId(11L);
        otherArtist.setCategoryId(1L);
        otherArtist.setTitle("Other Artist Podcast");
        otherArtist.setVisibility(ContentVisibility.PUBLIC);
        otherArtist.setIsActive(true);
        podcastRepository.save(otherArtist);

        Page<Podcast> page = podcastRepository.findByArtistIdAndIsActiveTrue(10L, PageRequest.of(0, 10));

        assertThat(page.getContent())
                .extracting(Podcast::getTitle)
                .containsExactly("Active Podcast");
    }

    @Test
    @DisplayName("findRecommended orders podcasts by episode count")
    void findRecommendedOrdersByEpisodeCount() {
        Podcast first = new Podcast();
        first.setArtistId(20L);
        first.setCategoryId(1L);
        first.setTitle("First Podcast");
        first.setVisibility(ContentVisibility.PUBLIC);
        first.setIsActive(true);
        first = podcastRepository.save(first);

        Podcast second = new Podcast();
        second.setArtistId(21L);
        second.setCategoryId(1L);
        second.setTitle("Second Podcast");
        second.setVisibility(ContentVisibility.PUBLIC);
        second.setIsActive(true);
        second = podcastRepository.save(second);

        jdbcTemplate.update(
                "INSERT INTO podcast_episodes (podcast_id, title, audio_url, duration_seconds, release_date, version) VALUES (?, ?, ?, ?, ?, ?)",
                first.getPodcastId(), "Ep 1", "url1", 300, java.sql.Date.valueOf("2025-01-01"), 0);
        jdbcTemplate.update(
                "INSERT INTO podcast_episodes (podcast_id, title, audio_url, duration_seconds, release_date, version) VALUES (?, ?, ?, ?, ?, ?)",
                first.getPodcastId(), "Ep 2", "url2", 200, java.sql.Date.valueOf("2025-01-02"), 0);
        jdbcTemplate.update(
                "INSERT INTO podcast_episodes (podcast_id, title, audio_url, duration_seconds, release_date, version) VALUES (?, ?, ?, ?, ?, ?)",
                second.getPodcastId(), "Ep A", "url3", 180, java.sql.Date.valueOf("2025-01-03"), 0);

        Page<Podcast> page = podcastRepository.findRecommended(PageRequest.of(0, 10));
        List<Podcast> results = page.getContent();

        assertThat(results)
                .hasSize(2)
                .extracting(Podcast::getPodcastId)
                .containsExactly(first.getPodcastId(), second.getPodcastId());
    }
}
