package com.revplay.musicplatform.playback.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.playback.entity.QueueItem;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS queue_items",
        "CREATE TABLE queue_items (" +
                "queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT NOT NULL, " +
                "song_id BIGINT, " +
                "episode_id BIGINT, " +
                "position INT NOT NULL, " +
                "created_at TIMESTAMP NOT NULL, " +
                "version BIGINT)"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Tag("integration")
class QueueItemRepositoryTest {

    private final QueueItemRepository queueItemRepository;

    @Autowired
    QueueItemRepositoryTest(QueueItemRepository queueItemRepository) {
        this.queueItemRepository = queueItemRepository;
    }

    @Test
    @DisplayName("findByUserIdForUpdate returns items ordered by position then queueId")
    void findByUserIdForUpdateOrdersByPosition() {
        QueueItem item1 = new QueueItem();
        item1.setUserId(1L);
        item1.setSongId(11L);
        item1.setPosition(2);
        item1.setCreatedAt(Instant.now());
        queueItemRepository.save(item1);

        QueueItem item2 = new QueueItem();
        item2.setUserId(1L);
        item2.setSongId(12L);
        item2.setPosition(1);
        item2.setCreatedAt(Instant.now());
        queueItemRepository.save(item2);

        QueueItem item3 = new QueueItem();
        item3.setUserId(2L);
        item3.setSongId(13L);
        item3.setPosition(1);
        item3.setCreatedAt(Instant.now());
        queueItemRepository.save(item3);

        List<QueueItem> results = queueItemRepository.findByUserIdForUpdate(1L);

        assertThat(results)
                .extracting(QueueItem::getPosition)
                .containsExactly(1, 2);
    }

    @Test
    @DisplayName("findTopByUserIdOrderByPositionDesc returns highest position")
    void findTopByUserIdOrderByPositionDescReturnsHighest() {
        QueueItem item1 = new QueueItem();
        item1.setUserId(3L);
        item1.setSongId(21L);
        item1.setPosition(1);
        item1.setCreatedAt(Instant.now());
        queueItemRepository.save(item1);

        QueueItem item2 = new QueueItem();
        item2.setUserId(3L);
        item2.setSongId(22L);
        item2.setPosition(5);
        item2.setCreatedAt(Instant.now());
        queueItemRepository.save(item2);

        QueueItem top = queueItemRepository.findTopByUserIdOrderByPositionDesc(3L).orElseThrow();

        assertThat(top.getPosition()).isEqualTo(5);
    }
}
