package com.revplay.musicplatform.audit.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.revplay.musicplatform.audit.entity.AdminAuditLog;
import com.revplay.musicplatform.audit.enums.AuditActionType;
import com.revplay.musicplatform.audit.enums.AuditEntityType;
import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
})
@org.springframework.boot.autoconfigure.domain.EntityScan(basePackages = "com.revplay.musicplatform")
@ActiveProfiles("test")
@Tag("integration")
class AdminAuditLogRepositoryTest {

    private final AdminAuditLogRepository adminAuditLogRepository;

    @Autowired
    AdminAuditLogRepositoryTest(AdminAuditLogRepository adminAuditLogRepository) {
        this.adminAuditLogRepository = adminAuditLogRepository;
    }

    @Test
    @DisplayName("findWithFilters filters by action and performedBy")
    @Sql(statements = {
            "DROP TABLE IF EXISTS admin_audit_logs",
            "CREATE TABLE admin_audit_logs (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "action VARCHAR(50) NOT NULL, " +
                    "performed_by BIGINT NOT NULL, " +
                    "entity_type VARCHAR(50) NOT NULL, " +
                    "entity_id BIGINT, " +
                    "description VARCHAR(500), " +
                    "timestamp TIMESTAMP, " +
                    "version BIGINT)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(1, 'PLAYLIST_CREATED', 10, 'PLAYLIST', 100, 'created', TIMESTAMP '2025-01-01 10:00:00', 0)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(2, 'PLAYLIST_UPDATED', 10, 'PLAYLIST', 101, 'updated', TIMESTAMP '2025-01-02 10:00:00', 0)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(3, 'PLAYLIST_CREATED', 11, 'PLAYLIST', 102, 'created', TIMESTAMP '2025-01-03 10:00:00', 0)"
    }, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
    void findWithFiltersFiltersByActionAndPerformedBy() {
        Page<AdminAuditLog> page = adminAuditLogRepository.findWithFilters(
                AuditActionType.PLAYLIST_CREATED,
                10L,
                AuditEntityType.PLAYLIST,
                null,
                null,
                PageRequest.of(0, 10));

        assertThat(page.getContent())
                .hasSize(1)
                .first()
                .extracting("id")
                .isEqualTo(1L);
    }

    @Test
    @DisplayName("findWithFilters filters by date range")
    @Sql(statements = {
            "DROP TABLE IF EXISTS admin_audit_logs",
            "CREATE TABLE admin_audit_logs (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "action VARCHAR(50) NOT NULL, " +
                    "performed_by BIGINT NOT NULL, " +
                    "entity_type VARCHAR(50) NOT NULL, " +
                    "entity_id BIGINT, " +
                    "description VARCHAR(500), " +
                    "timestamp TIMESTAMP, " +
                    "version BIGINT)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(1, 'PLAYLIST_CREATED', 10, 'PLAYLIST', 100, 'created', TIMESTAMP '2025-01-01 10:00:00', 0)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(2, 'PLAYLIST_CREATED', 10, 'PLAYLIST', 101, 'created', TIMESTAMP '2025-01-03 10:00:00', 0)",
            "INSERT INTO admin_audit_logs (id, action, performed_by, entity_type, entity_id, description, timestamp, version) VALUES " +
                    "(3, 'PLAYLIST_CREATED', 10, 'PLAYLIST', 102, 'created', TIMESTAMP '2025-01-06 10:00:00', 0)"
    }, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
    void findWithFiltersFiltersByDateRange() {
        LocalDateTime fromDate = LocalDateTime.of(2025, 1, 2, 0, 0);
        LocalDateTime toDate = LocalDateTime.of(2025, 1, 4, 23, 59);

        Page<AdminAuditLog> page = adminAuditLogRepository.findWithFilters(
                null,
                null,
                null,
                fromDate,
                toDate,
                PageRequest.of(0, 10));

        assertThat(page.getContent())
                .hasSize(1)
                .first()
                .extracting("id")
                .isEqualTo(2L);
    }
}
